deployment:
  version: "v1"
  images:
    app: "debug/image"

  port: 8080
  healthCheck:
    path: "/healthcheck"
    port: 8080

  octane:
    enabled: false

horizon:
  enabled: true

queueWorkers:
  enabled: true

reverb:
  enabled: true
  debug: true

hooks:
  postDeploy:
    enabled: true
    command:
      - "php artisan migrate --force -n"
      - "php artisan db:seed --force -n"

secretVolumes:
  - name: secret-name
    mountPath: /storage
    items:
      - key: filename-source
        path: filename-destination
