# Default values for laravel
deployment:
  enabled: true
  replicaCount: 2
  minAvailable: 1
  # Additional deployment annotations
  annotations: {}
  # Additional pod annotations
  podAnnotations: {}

  port: 80

  # Health check settings
  healthCheck:
    path: "/ping"
    port: 8000

  # start laravel with octane
  octane:
    enabled: false

  rollingUpdate:
    maxUnavailable: 0
    maxSurge: 1

  resources:
    requests:
      cpu: "50m"
      memory: "128Mi"
    limits:
      cpu: "500m"
      memory: "640Mi"

  pullPolicy: IfNotPresent

  version: ""

  images:
    app: ""

hooks:
  postDeploy:
    enabled: false
    command: "php artisan migrate --force -n"

#
# Main entry point settings
#
service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  annotations: {}
  #    kubernetes.io/ingress.class: nginx
  #    cert-manager.io/cluster-issuer: letsencrypt

  hosts: []
  #    - host: example.com
  #      paths:
  #        - '/'

redirect:
  enabled: true

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 60
  # targetMemoryUtilizationPercentage: 60

#
# Additional serviceAccount annotations
#
serviceAccountAnnotations: {}

#
# Environment settings
#
env:

envFrom: []

#
# Secrets to mount as volumes
#
secretVolumes: []
# - name: secret-name
#   items:
#     - key: filename-source
#       path: storage/filename-destination

#
# Enable horizon or standard queue workers
#
horizon:
  enabled: false
  resources:
    requests:
      cpu: "5m"
      memory: "192Mi"
    limits:
      cpu: "500m"
      memory: "640Mi"

queueWorkers:
  enabled: false
  queues:
    - name: "default"
      replica: 1
  resources:
    requests:
      cpu: "5m"
      memory: "96Mi"
    limits:
      cpu: "500m"
      memory: "640Mi"

#
# Enable reverb (websockets)
#
reverb:
  enabled: false
  port: 8080
  host: ws.example.com
  debug: false
  replicaCount: 1
  rollingUpdate:
    maxSurge: 1
  resources:
    requests:
      cpu: "10m"
      memory: "192Mi"
    limits:
      cpu: "100m"
      memory: "384Mi"

#
# Enable scheduler
#
scheduler:
  enabled: false
  cron: false
  resources:
    requests:
      cpu: "5m"
      memory: "64Mi"
    limits:
      cpu: "500m"
      memory: "640Mi"

options:
  disableDefaultEnv: false
  disableDefaultAppAffinity: false
  allowArmNodes: false
