{{- if .Values.app.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "keepsuit-service-laravel.name" . }}-app
  labels:
    {{- include "keepsuit-service-laravel.labels" . | nindent 4 }}
    app.kubernetes.io/component: "app"
spec:
  {{- if not .Values.app.autoscaling.enabled }}
  replicas: {{ .Values.app.deployment.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "keepsuit-service-laravel.commonSelectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: "app"
  strategy:
    type: RollingUpdate
    rollingUpdate:
      {{- with .Values.app.deployment.rollingUpdate }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
  revisionHistoryLimit: 3
  template:
    metadata:
      {{- with .Values.app.deployment.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "keepsuit-service-laravel.commonSelectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: "app"
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "keepsuit-service-laravel.name" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: "app"
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Values.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.app.deployment.octane }}
          command: [ "/scripts/entrypoint_laravel_app_octane.sh" ]
          {{- else }}
          command: [ "/scripts/entrypoint_laravel_app_fpm.sh" ]
          {{- end }}
          args: [ ]
          env:
            - name: APP_VERSION
              value: "{{ .Values.tag }}"
            {{- with .Values.env }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
            {{- with .Values.app.env }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          envFrom:
            {{- with .Values.envFrom }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
            {{- with .Values.app.envFrom }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 30
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 30
          resources:
            {{- with .Values.app.deployment.resources }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                  - key: "app.kubernetes.io/instance"
                    operator: In
                    values:
                      - {{ .Release.Name }}
                  - key: "app.kubernetes.io/version"
                    operator: In
                    values:
                      - "{{ .Values.tag }}"
                  - key: "app.kubernetes.io/component"
                    operator: In
                    values:
                      - "app"
              topologyKey: "kubernetes.io/hostname"
{{- end -}}