{{- if .Values.app.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "keepsuit-service-laravel.name" . }}-app
  labels:
    {{- include "keepsuit-service-laravel.labels" . | nindent 4 }}
    app.kubernetes.io/component: "app"
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "keepsuit-service-laravel.name" . }}-app
  minReplicas: {{ .Values.app.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.app.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.app.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: {{ .Values.app.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.app.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        targetAverageUtilization: {{ .Values.app.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
