{{- if .Values.app.ingress.enabled -}}
{{- $name := include "keepsuit-service-laravel.name" . -}}
{{- $svcPort := .Values.app.service.port -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $name }}-app
  labels:
    {{- include "keepsuit-service-laravel.labels" . | nindent 4 }}
    app.kubernetes.io/component: "app"
  annotations:
    {{- if .Values.app.redirect.enabled }}
    nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
    {{- end }}
    {{- with .Values.app.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- if .Values.app.ingress.tls }}
  tls:
    - hosts:
      {{- range .Values.app.ingress.tls }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ $name }}-app-tls
  {{- end }}
  rules:
    {{- range .Values.app.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ default "ImplementationSpecific" .pathType }}
            backend:
              service:
                name: {{ $name }}-app
                port:
                  number: {{ $svcPort }}
          {{- end }}
    {{- end }}
{{- end }}
