{{- if gt (int .Values.grpc.deployment.replicaCount) 1 }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "keepsuit-service-laravel.name" . }}-grpc
  labels:
    {{- include "keepsuit-service-laravel.labels" . | nindent 4 }}
    app.kubernetes.io/component: "grpc"
spec:
  minAvailable: {{ .Values.grpc.deployment.minAvailable }}
  selector:
    matchLabels:
      {{- include "keepsuit-service-laravel.commonSelectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: "grpc"
{{- end }}
