{{- if .Values.grpc.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "keepsuit-service-laravel.name" . }}-grpc
  labels:
    {{- include "keepsuit-service-laravel.labels" . | nindent 4 }}
    app.kubernetes.io/component: "grpc"
spec:
  {{- if not .Values.grpc.autoscaling.enabled }}
  replicas: {{ .Values.grpc.deployment.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "keepsuit-service-laravel.commonSelectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: "grpc"
  strategy:
    type: RollingUpdate
    rollingUpdate:
      {{- with .Values.grpc.deployment.rollingUpdate }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
  revisionHistoryLimit: 3
  template:
    metadata:
      {{- with .Values.grpc.deployment.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "keepsuit-service-laravel.commonSelectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: "grpc"
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "keepsuit-service-laravel.name" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: "grpc"
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Values.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: [ "/scripts/entrypoint_laravel_grpc.sh" ]
          args: [ ]
          env:
            - name: APP_VERSION
              value: "{{ .Values.tag }}"
            {{- with .Values.env }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
            {{- with .Values.grpc.env }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          envFrom:
            {{- with .Values.envFrom }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
            {{- with .Values.grpc.envFrom }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          ports:
            - name: grpc
              containerPort: 9090
              protocol: TCP
          readinessProbe:
            exec:
              command: [ "/usr/local/bin/grpc_health_probe", "-addr=:9090" ]
            initialDelaySeconds: 30
            periodSeconds: 30
          livenessProbe:
            exec:
              command: [ "/usr/local/bin/grpc_health_probe", "-addr=:9090" ]
            initialDelaySeconds: 30
            periodSeconds: 30
          resources:
            {{- with .Values.grpc.deployment.resources }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                  - key: "app.kubernetes.io/instance"
                    operator: In
                    values:
                      - {{ .Release.Name }}
                  - key: "app.kubernetes.io/version"
                    operator: In
                    values:
                      - "{{ .Values.tag }}"
                  - key: "app.kubernetes.io/component"
                    operator: In
                    values:
                      - "grpc"
              topologyKey: "kubernetes.io/hostname"
{{- end -}}