{{- if .Values.grpc.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "keepsuit-service-laravel.name" . }}-grpc
  labels:
    {{- include "keepsuit-service-laravel.labels" . | nindent 4 }}
    app.kubernetes.io/component: "grpc"
spec:
  type: {{ .Values.grpc.service.type }}
  ports:
    - port: {{ .Values.grpc.service.port }}
      targetPort: grpc
      protocol: TCP
      name: grpc
  selector:
    {{- include "keepsuit-service-laravel.commonSelectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: "grpc"
{{- end -}}