{{- if .Values.hooks.postDeploy.enabled -}}

apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "keepsuit-service-laravel.name" . }}-post-deploy
  labels:
    {{- include "keepsuit-service-laravel.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": "post-install,post-upgrade"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  template:
    metadata:
      annotations:
        "linkerd.io/inject": "disabled"
    spec:
      restartPolicy: Never
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: post-deploy-job
          image: {{ required "App image required" .Values.image.repository }}:{{ .Values.image.tag | default .Values.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/bin/sh", "-c"]
          args: {{ .Values.hooks.postDeploy.command | toJson }}
          env:
            - name: APP_VERSION
              value: "{{ .Values.tag }}"
            {{- with .Values.env }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          envFrom:
            {{- with .Values.envFrom }}
            {{- toYaml . | nindent 12 }}
            {{- end }}

{{ end }}