{{- if .Values.horizon.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "keepsuit-service-laravel.name" . }}-horizon
  labels:
    {{- include "keepsuit-service-laravel.labels" . | nindent 4 }}
    app.kubernetes.io/component: "horizon"
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "keepsuit-service-laravel.commonSelectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: "horizon"
  revisionHistoryLimit: 3
  template:
    metadata:
      labels:
        {{- include "keepsuit-service-laravel.commonSelectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: "horizon"
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "keepsuit-service-laravel.name" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: horizon
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Values.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: [ "/scripts/entrypoint_laravel_horizon.sh" ]
          args: [ ]
          resources:
            {{- with .Values.horizon.resources }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          env:
            - name: APP_VERSION
              value: "{{ .Values.tag }}"
            {{- with .Values.env }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
            {{- with .Values.grpc.env }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          envFrom:
            {{- with .Values.envFrom }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
            {{- with .Values.grpc.envFrom }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          lifecycle:
            preStop:
              exec:
                command: ["php", "artisan", "horizon:terminate"]

{{- end }}
