{{- if .Values.queueWorkers.enabled -}}

{{- $outer := . -}}
{{- range .Values.queueWorkers.workers -}}
{{- $queue := . -}}
{{- with $outer }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "keepsuit-service-laravel.name" . }}-queue-{{ required "Queue name is required" $queue.name }}
  labels:
    {{- include "keepsuit-service-laravel.labels" . | nindent 4 }}
    app.kubernetes.io/component: "queue-{{ $queue.name }}"
spec:
  {{- if $queue.replicas }}
  replicas: {{ $queue.replicas }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "keepsuit-service-laravel.commonSelectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: "queue-{{ $queue.name }}"
  revisionHistoryLimit: 3
  template:
    metadata:
     labels:
        {{- include "keepsuit-service-laravel.commonSelectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: "queue-{{ $queue.name }}"
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "keepsuit-service-laravel.name" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: queue-worker
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Values.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          terminationGracePeriodSeconds: {{ mul 2 (default 90 .$queue.timeout) }}
          command: [ "/scripts/entrypoint_laravel_queue.sh" ]
          args: [ ]
          resources:
            {{- with .Values.queueWorkers.resources }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          env:
            - name: APP_VERSION
              value: {{ .Values.tag }}
            - name: NAME
              value: {{ quote $queue.name }}
            {{- if $queue.queue }}
            - name: QUEUE
              value: {{ quote $queue.queue }}
            {{- end }}
            {{- if $queue.connection }}
            - name: CONNECTION
              value: {{ quote $queue.connection }}
            {{- end }}
            {{- if $queue.tries }}
            - name: TRIES
              value: {{ quote $queue.tries }}
            {{- end }}
            {{- if $queue.timeout }}
            - name: TIMEOUT
              value: {{ quote $queue.timeout }}
            {{- end }}
            {{- if $queue.maxJobs }}
            - name: MAX_JOBS
              value: {{ quote $queue.maxJobs }}
            {{- end }}
            {{- if $queue.maxTime }}
            - name: MAX_TIME
              value: {{ quote $queue.maxTime }}
            {{- end }}
            {{- with .Values.env }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
            {{- with .Values.queueWorkers.env }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          envFrom:
            {{- with .Values.envFrom }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
            {{- with .Values.queueWorkers.envFrom }}
            {{- toYaml . | nindent 12 }}
            {{- end }}

{{- end -}}
{{- end -}}

{{- end }}
