apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "keepsuit-service-laravel.serviceAccountName" . }}
  labels:
    {{- include "keepsuit-service-laravel.labels" . | nindent 4 }}
  {{- with .Values.serviceAccountAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
