{{- if .Values.temporal.enabled -}}

{{- $outer := . -}}
{{- range .Values.temporal.workers -}}
{{- $queue := . -}}
{{- with $outer }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "keepsuit-service-laravel.name" . }}-temporal-{{ required "Queue name is required" $queue.name }}
  labels:
    {{- include "keepsuit-service-laravel.labels" . | nindent 4 }}
    app.kubernetes.io/component: "temporal-{{ $queue.name }}"
spec:
  {{- if $queue.replicas }}
  replicas: {{ $queue.replicas }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "keepsuit-service-laravel.commonSelectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: "temporal-{{ $queue.name }}"
  revisionHistoryLimit: 3
  template:
    metadata:
     labels:
        {{- include "keepsuit-service-laravel.commonSelectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: "temporal-{{ $queue.name }}"
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      terminationGracePeriodSeconds: {{ mul 2 (default 90 $queue.timeout) }}
      serviceAccountName: {{ include "keepsuit-service-laravel.name" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: temporal-worker
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Values.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: [ "/scripts/entrypoint_laravel_temporal.sh" ]
          args: [ ]
          resources:
            {{- with .Values.temporal.resources }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          env:
            - name: APP_VERSION
              value: "{{ .Values.tag }}"
            - name: QUEUE
              value: {{ quote $queue.name }}
            {{- if $queue.workers }}
            - name: WORKERS
              value: {{ quote $queue.workers }}
            {{- end }}
            {{- if $queue.maxJobs }}
            - name: MAX_JOBS
              value: {{ quote $queue.maxJobs }}
            {{- end }}
            {{- if $queue.maxMemory }}
            - name: MAX_MEMORY
              value: {{ quote $queue.maxMemory }}
            {{- end }}
            {{- with .Values.env }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
            {{- with .Values.temporal.env }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          envFrom:
            {{- with .Values.envFrom }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
            {{- with .Values.temporal.envFrom }}
            {{- toYaml . | nindent 12 }}
            {{- end }}

{{- end -}}
{{- end -}}

{{- end }}
