apiVersion: v1
kind: Secret
metadata:
  name: {{ include "laravel-secrets.fullname" . }}
  labels:
    {{- include "laravel-secrets.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $value := .Values.data }}
  {{- $key | nindent 2 }}: {{ $value | b64enc }}
  {{- end }}
