{{- if .Values.deployment.enabled -}}

apiVersion: v1
kind: Service
metadata:
  name: {{ include "laravel.fullname" . }}
  labels:
    {{- include "laravel.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
  selector:
    app.kubernetes.io/name: {{ include "laravel.deployment-app.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}

{{- end -}}
