{{- if and .Values.app.enabled .Values.app.service.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "laravel.fullname" . }}-app
  labels:
    {{- include "laravel.componentLabels" (dict "root" . "component" "app") | nindent 4 }}
spec:
  type: {{ .Values.app.service.type }}
  ports:
    - port: {{ default .Values.app.port .Values.app.service.port }}
      targetPort: http
  selector:
    {{- include "laravel.appSelectorLabels" . | nindent 4 }}
{{- end -}}
