{{- if and .Values.app.enabled (gt (int .Values.app.replicas) 1) }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "laravel.fullname" . }}-app
  labels:
    {{- include "laravel.componentLabels" (dict "root" . "component" "app") | nindent 4 }}
spec:
  minAvailable: {{ .Values.app.minAvailable }}
  selector:
    matchLabels:
      {{- include "laravel.appSelectorLabels" . | nindent 6 }}
{{- end }}
