{{ define "laravel.deployment-queue-worker.name" -}}
{{ template "laravel.name" . }}-queue-worker
{{- end -}}

{{ define "laravel.deployment-queue-worker.fullname" -}}
{{ template "laravel.fullname" . }}-queue-worker
{{- end -}}

{{- if .Values.queueWorkers.enabled -}}

{{- $outer := . -}}
{{- range .Values.queueWorkers.queues -}}
{{- $queue := . -}}
{{- with $outer }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "laravel.deployment-queue-worker.fullname" . }}-{{ $queue.name }}
  labels:
    {{- include "laravel.labels" . | nindent 4 }}
    app.kubernetes.io/name: {{ template "laravel.deployment-queue-worker.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Values.deployment.version }}
    role: "queue"
spec:
  replicas: {{ default 1 $queue.replica }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ template "laravel.deployment-queue-worker.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  revisionHistoryLimit: 3
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ template "laravel.deployment-queue-worker.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/version: {{ .Values.deployment.version }}
        role: "queue"
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "laravel.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- if not .Values.options.allowArmNodes }}
      nodeSelector:
        kubernetes.io/arch: "amd64"
      {{- end }}
      containers:
        - name: queue-worker
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: {{ required "App image required" .Values.deployment.images.app }}:{{ required "App version" .Values.deployment.version }}
          imagePullPolicy: {{ .Values.deployment.pullPolicy }}
          resources:
            {{- with .Values.queueWorkers.resources }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          env:
            - name: CONTAINER_ROLE
              value: "queue"
            - name: QUEUE
              value: {{ quote $queue.name }}
            {{- if not .Values.options.disableDefaultEnv }}
            - name: LOG_CHANNEL
              value: "stderr"
            {{- end }}
            {{- with .Values.env }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          envFrom:
            {{- with .Values.envFrom }}
            {{- toYaml . | nindent 12 }}
            {{- end }}

{{- end -}}
{{- end -}}

{{- end }}
