{{- if .Values.hooks.postDeploy.enabled -}}
{{- $commands := default .Values.hooks.postDeploy.command .Values.hooks.postDeploy.commands -}}
{{- $command := $commands -}}
{{- if kindOf $commands | eq "slice" -}}
{{- $command = join " && " $commands -}}
{{- end -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "laravel.fullname" . }}-post-deploy
  labels:
    {{- include "laravel.componentLabels" (dict "root" . "component" "post-deploy") | nindent 4 }}
  annotations:
    "helm.sh/hook": "post-install,post-upgrade"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  template:
    metadata:
      labels:
        {{- include "laravel.componentSelectorLabels" (dict "root" . "component" "post-deploy") | nindent 8 }}
    spec:
      restartPolicy: Never
      {{- include "laravel.podSpecCommon" (dict "root" . "workload" (dict)) | nindent 6 }}
      containers:
        - name: post-deploy-job
          {{- with .Values.global.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: {{ include "laravel.image" . }}
          imagePullPolicy: {{ .Values.global.image.pullPolicy }}
          args: ["sh", "-c", {{ $command | squote }}]
          {{- with .Values.hooks.postDeploy.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          env:
            {{- include "laravel.env" (dict "root" . "workload" .Values.hooks.postDeploy "role" "post-deploy" "extra" (list (dict "name" "AUTORUN_LARAVEL_OPTIMIZE" "value" "false")) ) | nindent 12 }}
          {{- include "laravel.envFrom" (dict "root" . "workload" .Values.hooks.postDeploy) | nindent 10 }}
          {{- with .Values.global.secretVolumes }}
          volumeMounts:
            {{- include "laravel.secretVolumeMounts" $ | nindent 12 }}
          {{- end }}
      {{- with .Values.global.secretVolumes }}
      volumes:
        {{- include "laravel.secretVolumes" $ | nindent 8 }}
      {{- end }}
{{- end }}
