{{- if .Values.horizon.enabled -}}
{{- if .Values.horizon.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "laravel.fullname" . }}-horizon
  labels:
    {{- include "laravel.labels" . | nindent 4 }}
    app.kubernetes.io/name: {{ include "laravel.name" . }}-horizon
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: "{{ .Values.deployment.version }}"
    role: "horizon"
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "laravel.fullname" . }}-horizon
  minReplicas: {{ .Values.horizon.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.horizon.autoscaling.maxReplicas }}
  metrics:
  {{- if .Values.horizon.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.horizon.autoscaling.targetCPUUtilizationPercentage }}
  {{- end }}
  {{- if .Values.horizon.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.horizon.autoscaling.targetMemoryUtilizationPercentage }}
  {{- end }}
{{- end }}
{{- end }}
