{{- if gt (int .Values.deployment.replicaCount) 1 }}
{{- if .Capabilities.APIVersions.Has "policy/v1" }}
apiVersion: policy/v1
{{- else }}
apiVersion: policy/v1beta1
{{- end }}
kind: PodDisruptionBudget
metadata:
  name: {{ include "laravel.fullname" . }}
  labels:
    {{- include "laravel.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.deployment.minAvailable }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ template "laravel.deployment-app.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
