{{- if gt (int .Values.reverb.replicaCount) 1 }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "laravel.fullname" . }}-reverb
  labels:
    {{- include "laravel.labels" . | nindent 4 }}
    app.kubernetes.io/component: "reverb"
spec:
  minAvailable: {{ default 1 .Values.reverb.minAvailable }}
  selector:
    matchLabels:
      {{- include "laravel.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: "reverb"
{{- end }}
