{{- if .Values.reverb.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "laravel.fullname" . }}-reverb
  labels:
    {{- include "laravel.labels" . | nindent 4 }}
    app.kubernetes.io/component: "reverb"
spec:
  replicas: {{ default 1 .Values.reverb.replicaCount }}
  selector:
    matchLabels:
      {{- include "laravel.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: "reverb"
  strategy:
    type: RollingUpdate
    rollingUpdate:
      {{- with .Values.reverb.rollingUpdate }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
  revisionHistoryLimit: 3
  template:
    metadata:
      labels:
        {{- include "laravel.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: "reverb"
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "laravel.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- if not .Values.options.allowArmNodes }}
      nodeSelector:
        kubernetes.io/arch: "amd64"
      {{- end }}
      containers:
        - name: reverb
          image: {{ required "App image required" .Values.deployment.images.app }}:{{ required "App version" .Values.deployment.version }}
          imagePullPolicy: {{ .Values.deployment.pullPolicy }}
          args:
            - "php"
            - "artisan"
            {{- if (default false .Values.reverb.debug) }}
            - "--debug"
            {{- end }}
            - "--host=0.0.0.0"
            - "--port={{ required "Reverb port is required" .Values.reverb.port }}"
            - "reverb:start"
          ports:
            - name: reverb
              containerPort: {{ int (required "Reverb port is required" .Values.reverb.port) }}
              protocol: TCP
          resources:
            {{- with .Values.reverb.resources }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          env:
            {{- if not .Values.options.disableDefaultEnv }}
            - name: LOG_CHANNEL
              value: "stderr"
            {{- end }}
            {{- if gt (int .Values.reverb.replicaCount) 1 }}
            - name: REVERB_SCALING_ENABLED
              value: "true"
            {{- end }}
            {{- with .Values.env }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          envFrom:
            {{- with .Values.envFrom }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          volumeMounts:
            {{- range .Values.secretVolumes }}
            {{- $volume := . -}}
            {{- range .items }}
            - name: {{ $volume.name }}
              mountPath: {{ $volume.mountPath | default "/" | trimSuffix "/" }}/{{ .key }}
              subPath: {{ .key }}
              readOnly: true
            {{- end }}
            {{- end }}
          readinessProbe:
            tcpSocket:
              port: {{ .Values.reverb.port }}
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: {{ .Values.reverb.port }}
            initialDelaySeconds: 30
            periodSeconds: 30
      volumes:
      {{- range .Values.secretVolumes }}
        - name: {{ .name }}
          secret:
            secretName: {{ .name }}
            items:
              {{- toYaml .items | nindent 14 }}
      {{- end }}
{{- end }}
