{{- if .Values.reverb.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "laravel.fullname" . }}-reverb
  labels:
    {{- include "laravel.labels" . | nindent 4 }}
    app.kubernetes.io/component: "reverb"
spec:
    type: {{ .Values.service.type }}
    ports:
        - port: {{ .Values.reverb.port }}
          targetPort: reverb
    selector:
      {{- include "laravel.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: "reverb"
{{- end -}}
