{{- if and .Values.reverb.enabled .Values.reverb.service.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "laravel.fullname" . }}-reverb
  labels:
    {{- include "laravel.componentLabels" (dict "root" . "component" "reverb") | nindent 4 }}
spec:
  type: {{ .Values.reverb.service.type }}
  ports:
    - port: {{ default .Values.reverb.port .Values.reverb.service.port }}
      targetPort: reverb
  selector:
    {{- include "laravel.componentSelectorLabels" (dict "root" . "component" "reverb") | nindent 4 }}
{{- end -}}
