{{ define "laravel.cronjob-scheduler.name" -}}
{{ template "laravel.name" . }}-scheduler
{{- end -}}

{{ define "laravel.cronjob-scheduler.fullname" -}}
{{ template "laravel.fullname" . }}-scheduler
{{- end -}}

{{- if and .Values.scheduler.enabled .Values.scheduler.cron -}}

apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ include "laravel.cronjob-scheduler.fullname" . }}
  labels:
    {{- include "laravel.labels" . | nindent 4 }}
    app.kubernetes.io/name: {{ template "laravel.cronjob-scheduler.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  schedule: "* * * * *"
  startingDeadlineSeconds: 59
  jobTemplate:
    spec:
      template:
        spec:
        {{- with .Values.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 12 }}
        {{- end }}
          serviceAccountName: {{ include "laravel.serviceAccountName" . }}
          securityContext:
            {{- toYaml .Values.podSecurityContext | nindent 12 }}
          containers:
          - name: scheduler
            image: {{ required "App image required" .Values.deployment.images.app }}:{{ required "App version" .Values.deployment.version }}
            imagePullPolicy: {{ .Values.deployment.pullPolicy }}
            resources:
              {{- with .Values.scheduler.resources }}
              {{- toYaml . | nindent 14 }}
              {{- end }}
            args:
              - php
              - artisan
              - schedule:run
            env:
              - name: CONTAINER_ROLE
                value: "scheduler"
              - name: LOG_CHANNEL
                value: "stderr"
              {{- with .Values.env }}
              {{- toYaml . | nindent 14 }}
              {{- end }}
            envFrom:
              {{- with .Values.envFrom }}
              {{- toYaml . | nindent 14 }}
              {{- end }}
          restartPolicy: OnFailure
{{- end }}