#
# Service name
#
name: ""

#
# App version
#
tag: "latest"

#
# Image settings
#
image:
  repository: ""
  pullPolicy: IfNotPresent

#
# Environment settings
#
env:
  - name: LOG_CHANNEL
    value: "stderr"

envFrom: []

#
# Global options
#
options:
  disableDefaultEnv: false
  disableDefaultAppAffinity: false

#
# Additional serviceAccount annotations
#
serviceAccountAnnotations: {}

#
# Helm lifecycle hooks
#
hooks:
  postDeploy:
    enabled: false
    command: ["php artisan migrate --force -n"]

#
# App settings
#
app:
  enabled: true

  #
  # App only environment settings
  #
  env:
  envFrom: [ ]

  deployment:
    octane: false

    replicaCount: 2
    minAvailable: 1

    annotations: {}
    #   config.linkerd.io/skip-outbound-ports: "3306,6379"
    #   linkerd.io/inject: enabled

    podAnnotations: {}

    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1

    resources:
      requests:
        cpu: "25m"
        memory: "64Mi"
      limits:
        cpu: "600m"
        memory: "512Mi"

  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 10
    targetCPUUtilizationPercentage: 60

  service:
    type: ClusterIP
    port: 80

  ingress:
    enabled: false
    annotations: {}
    #    kubernetes.io/ingress.class: nginx
    #    cert-manager.io/cluster-issuer: letsencrypt
    tls: []
    #   - example.com
    hosts: []
    #    - host: example.com
    #      paths:
    #          - path: /
    #            pathType: ImplementationSpecific

  redirect:
    enabled: true

#
# Grpc settings
#
grpc:
  enabled: false

  #
  # Grpc only environment settings
  #
  env:
  envFrom: [ ]

  deployment:
    replicaCount: 2
    minAvailable: 1

    annotations: {}
    #   config.linkerd.io/skip-outbound-ports: "3306,6379"
    #   linkerd.io/inject: enabled

    podAnnotations: {}

    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1

    resources:
      requests:
        cpu: "25m"
        memory: "64Mi"
      limits:
        cpu: "600m"
        memory: "512Mi"

  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 10
    targetCPUUtilizationPercentage: 60

  service:
    type: ClusterIP
    port: 9090

#
# Enable horizon or standard queue workers
#
horizon:
  enabled: false

  #
  # Horizon only environment settings
  #
  env:
  envFrom: [ ]

  resources:
    requests:
      cpu: "25m"
      memory: "128Mi"
    limits:
      cpu: "600m"
      memory: "512Mi"

queueWorkers:
  enabled: false

  #
  # Queue only environment settings
  #
  env:
  envFrom: [ ]

  queues:
    - name: "default"
      replica: 1
      # tries: 1
      # timeout: 90
      # maxJobs: 0
      # maxTime: 0
  resources:
    requests:
      cpu: "25m"
      memory: "64Mi"
    limits:
      cpu: "600m"
      memory: "512Mi"

#
# Enable scheduler
#
scheduler:
  enabled: false

  #
  # Scheduler only environment settings
  #
  env:
  envFrom: [ ]

  resources:
    requests:
      cpu: "25m"
      memory: "64Mi"
    limits:
      cpu: "600m"
      memory: "512Mi"
